app:
  swagger-server-url: https://languagedive.bryanrodriguez.tech

spring:
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
