CREATE TYPE source_type AS ENUM (
	'EPUB',
	'TXT'
);

CREATE TYPE vocabulary_status AS ENUM (
	'NEW',
	'LEVEL_2',
	'LEVEL_3',
	'LEVEL_4',
	'LEVEL_5',
	'LEARNED',
	'IGNORED'
);

CREATE TABLE IF NOT EXISTS "User" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "username" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL,
    "updatedAt" TIMESTAMPTZ,
    PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "Course" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" VARCHAR(255) NOT NULL,
    "description" VARCHAR(255),
    "coverUrl" VARCHAR(255),
    "sourceType" source_type NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL,
    "userId" BIGINT NOT NULL,
    PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "Lesson" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" VARCHAR(255) NOT NULL,
    "content" TEXT NOT NULL,
    "lessonOrder" INTEGER NOT NULL,
    "courseId" BIGINT NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL,
    "updatedAt" TIMESTAMPTZ,
    "wordCount" INTEGER,
    PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "UserCourseProgress" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" BIGINT NOT NULL,
    "courseId" BIGINT NOT NULL,
    "completedLessons" INTEGER,
    "totalLessons" INTEGER,
    "progressPercentage" INTEGER,
    "lastAccessedAt" TIMESTAMPTZ,
    PRIMARY KEY("id")
    );


CREATE TABLE IF NOT EXISTS "UserLessonProgress" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" BIGINT NOT NULL,
    "lessonId" BIGINT NOT NULL,
    "lastReadingPosition" INTEGER,
    "completed" BOOLEAN,
    "completedAt" TIMESTAMPTZ,
    PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "VocabularyEntry" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "term" VARCHAR(255) NOT NULL UNIQUE,
    "meaning" VARCHAR(255) NOT NULL,
    "status" vocabulary_status NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL,
    "updatedAt" TIMESTAMPTZ,
    "userId" BIGINT NOT NULL,
    "timesSeen" INTEGER,
    "lastSeenAt" TIMESTAMPTZ,
    PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "ReadingSession" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" BIGINT NOT NULL,
    "lessonId" BIGINT NOT NULL,
    "startedAt" TIMESTAMPTZ,
    "completedAt" TIMESTAMPTZ,
    PRIMARY KEY("id")
);



ALTER TABLE "Course"
    ADD FOREIGN KEY("userId") REFERENCES "User"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "Lesson"
    ADD FOREIGN KEY("courseId") REFERENCES "Course"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "UserCourseProgress"
    ADD FOREIGN KEY("userId") REFERENCES "User"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "UserCourseProgress"
    ADD FOREIGN KEY("courseId") REFERENCES "Course"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "UserLessonProgress"
    ADD FOREIGN KEY("userId") REFERENCES "User"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "UserLessonProgress"
    ADD FOREIGN KEY("lessonId") REFERENCES "Lesson"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "VocabularyEntry"
    ADD FOREIGN KEY("userId") REFERENCES "User"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "ReadingSession"
    ADD FOREIGN KEY("userId") REFERENCES "User"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ReadingSession"
    ADD FOREIGN KEY("lessonId") REFERENCES "Lesson"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;