CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS course (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    cover_url VARCHAR(255),
    source_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS lesson (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    lesson_order INTEGER NOT NULL,
    course_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    word_count INTEGER,
    PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS user_course_progress (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    completed_lessons INTEGER,
    total_lessons INTEGER,
    progress_percentage INTEGER,
    last_accessed_at TIMESTAMPTZ,
    PRIMARY KEY(id),
    UNIQUE(course_id, user_id)
);


CREATE TABLE IF NOT EXISTS user_lesson_progress (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    lesson_id BIGINT NOT NULL,
    last_reading_position INTEGER,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMPTZ,
    PRIMARY KEY(id),
    UNIQUE(lesson_id, user_id)
);


CREATE TABLE IF NOT EXISTS vocabulary_entry (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    term VARCHAR(255) NOT NULL,
    meaning VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    user_id BIGINT NOT NULL,
    times_seen INTEGER,
    last_seen_at TIMESTAMPTZ,
    PRIMARY KEY(id),
    UNIQUE(term, user_id)
);


CREATE TABLE IF NOT EXISTS reading_session (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    lesson_id BIGINT NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS refresh_token (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY(id)
);



ALTER TABLE course
    ADD FOREIGN KEY(user_id) REFERENCES users(id)
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE lesson
    ADD FOREIGN KEY(course_id) REFERENCES course(id)
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE user_course_progress
    ADD FOREIGN KEY(user_id) REFERENCES users(id)
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE user_course_progress
    ADD FOREIGN KEY(course_id) REFERENCES course(id)
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE user_lesson_progress
    ADD FOREIGN KEY(user_id) REFERENCES users(id)
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE user_lesson_progress
    ADD FOREIGN KEY(lesson_id) REFERENCES lesson(id)
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE vocabulary_entry
    ADD FOREIGN KEY(user_id) REFERENCES users(id)
        ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE reading_session
    ADD FOREIGN KEY(user_id) REFERENCES users(id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE reading_session
    ADD FOREIGN KEY(lesson_id) REFERENCES lesson(id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE refresh_token
    ADD FOREIGN KEY(user_id) REFERENCES users(id)
        ON UPDATE NO ACTION ON DELETE CASCADE;
